project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Ex / In Class Ex
        menu: 
          - text: Hands-on Ex 1 - Chap 1 Geospatial Data Wrangling with R
            href: hands_on_ex/ex_1/ex_1.qmd
          - text: Hands-on Ex 1 - Chap 2 Choropleth Mapping with R
            href: hands_on_ex/ex_1/ex_1_2.qmd
          - text: In-Class Ex 1 - Chap 3 Spatial Weights and Applications
            href: in_class/ex_1/in_class_ex_1.qmd
          - text: Hands-on Ex 2 - Chap 4 Global and Local Measures of Spatial Autocorrelation
            href: hands_on_ex/ex_2/ex_2.qmd
          - text: In-Class Ex 2 - Loading data + prepare data for take home Ex 1
            href: in_class/ex_2/ex_2.qmd
          - text: Take-Home Ex 1 
            href: take_home_ex/ex_1/ex_1.qmd
          - text: Hands-on Ex 3 - Chap 5 Geographical Segmentation with Spatially Constrained Clustering Techniques
            href: hands_on_ex/ex_3/ex_3.qmd     
          - text: In-Class Ex 3 - Adding Clust Geo Chap 5 Geographical Segmentation with Spatially Constrained Clustering Techniques
            href: in_class/ex_3/ex_3.qmd  
          - text: Take-Home Ex 2 
            href: take_home_ex/ex_2/ex_2.qmd 
          - text: Hands-on Ex 4 + In Class 4 - Chap 6 Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method
            href: hands_on_ex/ex_4/ex_4.qmd  
          - text: In-Class Ex 5 - 
            href: in_class/ex_5/ex_5.qmd  
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

